name: 'snowflake_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'snowflake_dbt'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  # - "dbt_modules"
  # - "logs"


# Configuring models
models:
  snowflake_dbt:
    # Config indicated by + and applies to all files under models/example/
    +materialized: table
    staging:
      database: DBT_STAGING
      schema: TPCH
      +materialized: view
    dwh:
      database: DBT_DWH
      schema: TPCH
      +materialized: table
